/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three"
import React, { forwardRef, useImperativeHandle, useRef } from "react"
import { ObjectType } from "cgv/domains/movement"

type posNumber = [number,number,number]
type argsCone = [number?,number?,number?,number?,boolean?,number?,number?]
type argsTorus = [number?,number?,number?,number?,number?]

const markerData = {
    [ObjectType.Pedestrian]: {
        cone: {
            position: [0, 55, 0] as posNumber,
            args: [6, 10, 8] as argsCone,
        },
        torus: {
            position: [0, 4, 0] as posNumber,
            args: [23, 0.4, 8, 50] as argsTorus,
        },
    },
    [ObjectType.Cyclist]: {
        cone: {
            position: [0, 70, 0] as posNumber,
            args: [6, 10, 8] as argsCone,
        },
        torus: {
            position: [0, 4, 0] as posNumber,
            args: [30, 0.4, 8, 50]  as argsTorus,
        },
    },
    [ObjectType.Car]: {
        cone: {
            position: [0, 70, 0] as posNumber,
            args: [6, 10, 8]  as argsCone,
        },
        torus: {
            position: [0, 4, 0] as posNumber,
            args: [60, 0.4, 8, 50] as argsTorus,
        },
    },
}

export const Marker = forwardRef((props:{type:ObjectType}, ref) => {
    const group = useRef<any>()
    const coneData= markerData[props.type].cone
    const torusData= markerData[props.type].torus

    useImperativeHandle(ref, () => ({
        updatePosition(x: number, y: number, z: number) {
            group.current.position.y = y
            group.current.position.z = z
            group.current.position.x = x
        },
    }))

    return (
        <group ref={group}>
            <mesh position={coneData.position} rotation={[Math.PI, 0, 0]}>
                <coneBufferGeometry args={coneData.args} />
                <meshBasicMaterial color={"red"} side={THREE.DoubleSide} />
            </mesh>
            <mesh position={torusData.position} rotation={[Math.PI / 2, 0, 0]}>
                <torusBufferGeometry args={torusData.args} />
                <meshBasicMaterial color={"red"} side={THREE.DoubleSide} />
            </mesh>
        </group>
    )
})
