/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three"
import React, { useEffect, useMemo, useRef } from "react"
import { useGLTF, useAnimations } from "@react-three/drei"
import { GLTF, SkeletonUtils } from "three-stdlib"
import { AnimationClip, Group } from "three"
import { useFrame, useGraph } from "@react-three/fiber"
import { framePositions, movObject, useMovementStore } from "./useMovementStore"
import { RemyPlace } from "./remyplace"
import { render } from "react-dom"

export default function MovementLogicSmallScreen(props: { data: framePositions | null; id: string }) {
    const object = useRef<any>()
    const data = props.data

    useEffect(() => {
        if (data) {
            const position = data.position as number[]
            const direction = data.direction as number[]
            object.current.updatePosition(
                position[0],
                position[1],
                position[2],
                -Math.atan2(direction[2], direction[0]) + Math.PI / 2,
                Math.round(Math.random() * 500)
            )
        }
    }, [object, props])

    return (
        <>
            <RemyPlace id={props.id} ref={object}></RemyPlace>
        </>
    )
}
